### ISSUE TITLE
Provide a way to cache the pages

### ISSUE THREAD

**Issue by gajus** [Binaryify/express-middleware-seo#1]
I'd like to use https://www.npmjs.com/package/lru-cache to cache the pages for certain amount of time.

The interface should be using the [Map](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map) interface to prevent issues such as this https://github.com/isaacs/node-lru-cache/issues/109

**Comment by Binaryify** [comment]
I don't think this is necessary, because the search engine crawler access frequency is very low
