### ISSUE TITLE
The middleware hangs indefinitely if Chrome is not installed on the system

### ISSUE THREAD

**Issue by gajus** [Binaryify/express-middleware-seo#2]
Instead, should either crash or produce a warning and skip the middleware.

**Comment by Binaryify** [comment]
Will improve this

**Comment by Binaryify** [comment]
@gajus 
Fix it

**Comment by gajus** [comment]
I moved away to using https://github.com/gajus/usus. Though, thank you.

**Comment by Binaryify** [comment]
@gajus 
That project is nice~
